### PR TITLE
DM-21230: Minor compatibility/efficiency improvement

### PR DESCRIPTION
**Pull request by isullivan**

### CODE REVIEW

**Comment by mrawls** [comment]
`CompareWarp-DCR-Ppdb-Compare-HighRes-Template` and `CompareWarp-DCR-Ppdb-Compare` both have some leftover text blocks from my old analyses that don't apply anymore, please remove those. Please also give an overview of the actual reruns you'll be comparing at the start of each notebook (you do this nicely in one but not the other) and maybe write a couple sentences at the end summing up how they compare.

`DM-21230-Compare-CW-and-DCR-ap_pipe-output` doesn't have any explanatory text and it could use some.

**Comment by mrawls** [comment]
Would it be possible to do all the rerun comparisons in 1-2 notebooks instead of 3, I wonder?

**Comment by isullivan** [comment]
I've condensed the three notebooks down to one, and expanded the text. Is it in a good state to merge?

**Comment by mrawls** [comment]
This is loads better! A couple final nitpicks
* inconsistency between whether you're loading plotting scripts from `mrawls` or `sullivan` path on lsst-dev near the start
* missing `plotDiaObjectsOnSky` plot for one of the 3 reruns
* looks like you tried to embed a screenshot png into the notebook but it doesn't show up for me when I view the notebook on github, so maybe there is another way you can refer to this figure?

**Pull request merged**
